version: '2'
networks:
  microservice-network:
    external: true
services:
  eurekaserver:
    image: microservice-eurekasvr:1.0
    mem_limit: "1073741824"
    container_name: eurekaserver
    ports:
       - "8761:8761"
    networks:
      - microservice-network
  configserver:
    image: microservice-confsvr:1.0
    mem_limit: "1073741824"
    container_name: configserver
    ports:
       - "8888:8888"
    networks:
      - microservice-network
    environment:
      PROFILE: "default"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: 8761
  licensingservice:
    image: microservices-licensing-service:1.0
    mem_limit: "1073741824"
    container_name: licensingservice
    depends_on:
      - configserver
    ports:
      - "8080:8080"
    networks:
      - microservice-network
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      SERVER_PORT:   "8080"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      DATABASESERVER_PORT: "5432"
      KAFKASERVER_URI: "192.168.223.165"
      ZKSERVER_URI: "192.168.223.165"
      EUREKASERVER_PORT: "8761"
      KAFKASERVER_PORT: "9092"
      REDIS_URI: "microservice-redis"
      REDIS_PORT: "6379"
  organizationservice:
    image: microservices-organization-service:1.0
    mem_limit: "1073741824"
    container_name: organizationservice
    depends_on:
      - configserver
      - eurekaserver
    ports:
      - "8082:8082"
    networks:
      - microservice-network
    environment:
      SERVER_PORT: "8082"
      PROFILE: "default"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      DATABASESERVER_PORT: "5432"
      EUREKASERVER_PORT: "8761"
      KAFKASERVER_URI: "192.168.223.165"
      ZKSERVER_URI: "192.168.223.165"
  zuulserver:
    image: microservices-zuulsvr:1.0
    mem_limit: "1073741824"
    container_name: zuulserver
    mem_limit: "1073741824"
    depends_on:
      - eurekaserver
      - configserver
    ports:
      - "5555:5555"
    networks:
      - microservice-network
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_PORT:   "8888"
      EUREKASERVER_PORT: "8761"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
