server:
  port: 8081

spring:
  cloud:
    stream:
      bindings:
        inboundOrgChanges:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
        binder:
          zkNodes: localhost
          brokers: localhost
redis.server: "localhost"
redis.port: 6379
#security:
#  oauth2:
#   resource:
#      userInfoUri: http://localhost:8901/auth/user
#security:
#  oauth2:
 #   resource:
#      token-info-uri: http://localhost:9191/oauth/check_token
#    client:
#      client-id: mobile
#      client-secret: pin

eureka:
  instance:
    preferIpAddress: true
    ip-address:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
