server:
  port: 8082

spring:
  cloud:
    stream:
      bindings:
        output:
            destination:  orgChangeTopic
            content-type: application/json
        kafka:
          binder:
            zkNodes: localhost
            brokers: localhost

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

#security:
#  oauth2:
#    resource:
#      token-info-uri: http://localhost:9191/oauth/check_token
#    client:
#      client-id: mobile
#      client-secret: pin


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

        